### ISSUE TITLE
Critical service error: add-view issue (role "ocdskfpguest" does not exist)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#142]
**Which service is affected?**

Kingfisher Views
process.kingfisher.open-contracting.org

**What were you trying to do?**

Add a view for collection 1434

```bash
ssh ocdskfp@process.kingfisher.open-contracting.org
cd ocdskingfisherviews/
source .ve/bin/activate
python ocdskingfisher-views-cli add-view 1434 "Created by Duncan for CoST Honduras feedback."
```

**What error did you receive?**

```
2020-09-15 00:35:36,214 - 17658 - ocdskingfisher.views.cli - INFO - Running add-view
2020-09-15 00:35:36,272 - 17658 - ocdskingfisher.views.add-view - INFO - Added collection_1434
2020-09-15 00:35:36,272 - 17658 - ocdskingfisher.views.add-view - INFO - Running refresh-views collection_1434
2020-09-15 00:35:36,277 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 001-functions
2020-09-15 00:35:36,283 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.005937943235039711s
2020-09-15 00:35:36,283 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 002-tmp_release_and_parties
2020-09-15 00:36:08,462 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 32.17919485270977s
2020-09-15 00:36:08,463 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 003-buyer-procuringentity-tenderer
2020-09-15 00:36:08,633 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.16979467682540417s
2020-09-15 00:36:08,633 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 004-planning
2020-09-15 00:36:08,702 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.06873058155179024s
2020-09-15 00:36:08,702 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 005-tender
2020-09-15 00:36:08,789 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.0874169860035181s
2020-09-15 00:36:08,789 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 006-awards
2020-09-15 00:36:08,889 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.09970817901194096s
2020-09-15 00:36:08,890 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 007-contracts
2020-09-15 00:36:09,089 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.19919386878609657s
2020-09-15 00:36:09,089 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 008-release
2020-09-15 00:36:09,165 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.07616681233048439s
2020-09-15 00:36:09,165 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 009-drop-tmp_release_summary
2020-09-15 00:36:09,182 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.016263093799352646s
2020-09-15 00:36:09,182 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 998-foreign-key-relationships
2020-09-15 00:36:09,192 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.009587312117218971s
2020-09-15 00:36:09,192 - 17658 - ocdskingfisher.views.refresh-views - INFO - Running 999-docs
2020-09-15 00:36:09,215 - 17658 - ocdskingfisher.views.refresh-views - INFO - Time: 0.023075323551893234s
2020-09-15 00:36:09,215 - 17658 - ocdskingfisher.views.refresh-views - INFO - Total time: 32.942343855276704s
2020-09-15 00:36:09,215 - 17658 - ocdskingfisher.views.add-view - INFO - Running field-counts collection_1434
2020-09-15 00:36:09,252 - 17658 - ocdskingfisher.views.field-counts - INFO - Processing collection ID 1434
2020-09-15 00:36:09,488 - 17658 - ocdskingfisher.views.field-counts - INFO - Time for collection ID 1434: 0.2350090928375721s
2020-09-15 00:36:09,489 - 17658 - ocdskingfisher.views.field-counts - INFO - Total time: 0.24398510344326496s
2020-09-15 00:36:09,490 - 17658 - ocdskingfisher.views.add-view - INFO - Running correct-user-permissions
Traceback (most recent call last):
  File "ocdskingfisher-views-cli", line 5, in <module>
    cli()
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/cli.py", line 193, in add_view
    ctx.invoke(correct_user_permissions)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/cli.py", line 381, in correct_user_permissions
    cursor.execute(sql.SQL('GRANT USAGE ON SCHEMA public TO {user}').format(user=user))
psycopg2.errors.UndefinedObject: role "ocdskfpguest" does not exist
```

**What is your environment?**

n/a

**Did you attempt a fix?**

No

**How soon do you need a fix?**

ASAP - publisher needs feedback this week.

**Comment by jpmckinney** [comment]
I deleted that user earlier, but forgot to run `DELETE FROM views.read_only_user WHERE username = 'ocdskfpguest';` I'll update the instructions at https://ocdsdeploy.readthedocs.io/en/latest/deploy/update.html#delete-a-postgresql-user

In any case, the schema will have been created. correct-user-permissions is only run after everything else:

    \dt view_data_collection_1434

returns:

```
                                     List of relations
          Schema           |                     Name                     | Type  |  Owner  
---------------------------+----------------------------------------------+-------+---------
 view_data_collection_1434 | award_documents_summary                      | table | ocdskfp
 view_data_collection_1434 | award_items_summary                          | table | ocdskfp
 view_data_collection_1434 | award_suppliers_summary                      | table | ocdskfp
 view_data_collection_1434 | awards_summary_no_data                       | table | ocdskfp
 view_data_collection_1434 | buyer_summary                                | table | ocdskfp
 view_data_collection_1434 | contract_documents_summary                   | table | ocdskfp
 view_data_collection_1434 | contract_implementation_documents_summary    | table | ocdskfp
 view_data_collection_1434 | contract_implementation_milestones_summary   | table | ocdskfp
 view_data_collection_1434 | contract_implementation_transactions_summary | table | ocdskfp
 view_data_collection_1434 | contract_items_summary                       | table | ocdskfp
 view_data_collection_1434 | contract_milestones_summary                  | table | ocdskfp
 view_data_collection_1434 | contracts_summary_no_data                    | table | ocdskfp
 view_data_collection_1434 | field_counts                                 | table | ocdskfp
 view_data_collection_1434 | note                                         | table | ocdskfp
 view_data_collection_1434 | parties_summary_no_data                      | table | ocdskfp
 view_data_collection_1434 | planning_documents_summary                   | table | ocdskfp
 view_data_collection_1434 | planning_milestones_summary                  | table | ocdskfp
 view_data_collection_1434 | planning_summary                             | table | ocdskfp
 view_data_collection_1434 | procuringentity_summary                      | table | ocdskfp
 view_data_collection_1434 | release_summary                              | table | ocdskfp
 view_data_collection_1434 | selected_collections                         | table | ocdskfp
 view_data_collection_1434 | tender_documents_summary                     | table | ocdskfp
 view_data_collection_1434 | tender_items_summary                         | table | ocdskfp
 view_data_collection_1434 | tender_milestones_summary                    | table | ocdskfp
 view_data_collection_1434 | tender_summary                               | table | ocdskfp
 view_data_collection_1434 | tenderers_summary                            | table | ocdskfp
(26 rows)
```

**Comment by duncandewhurst** [comment]
I get the following error when I run `\dt view_data_collection_1434` whilst connected via psql as ocdskfp:

```
Did not find any relation named "view_data_collection_1434".
```

Similarly, when connected as ocdskfpreadonly via a notebook, I can't query any of the tables in the views schema, e.g.

```
 * postgresql://ocdskfpreadonly:***@postgres-readonly.kingfisher.open-contracting.org/ocdskingfisherprocess
(psycopg2.ProgrammingError) relation "field_counts" does not exist
LINE 1: select * from field_counts
                      ^

[SQL: select * from field_counts]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by jpmckinney** [comment]
Sorry, had to be `\dt view_data_collection_1434.*` instead.

You can't select from field_counts unless you first set the search path (that's just how it is in PostgreSQL).

Try `SELECT * FROM view_data_collection_1434.field_counts`

**Comment by duncandewhurst** [comment]
Odd, I had already set the search path before selecting from field_counts, but it still didn't work. Anyway, it seems to be working now. Thanks!
