### ISSUE TITLE
Critical service error - add-view

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-views#168]
**Which service is affected?**

Kingfisher Views
ocdskfp@process.kingfisher.open-contracting.org

**What were you trying to do?**

Create a view.

I had previously deleted a view with the same name, in case that is relevant.

```
python ocdskingfisher-views-cli add-view 1530,1531,1532 "Created by Duncan for Portugal data review."
```

**What error did you receive?**

```
2020-11-05 23:19:50,093 - 7589 - ocdskingfisher.views.cli - INFO - Running add-view
2020-11-05 23:19:50,112 - 7589 - ocdskingfisher.views.add-view - INFO - Arguments: collections=(1530, 1531, 1532) note=Created by Duncan for Portugal data review. name=None tables_only=False
2020-11-05 23:19:50,123 - 7589 - ocdskingfisher.views.add-view - INFO - Added collection_1530_1531_1532
2020-11-05 23:19:50,123 - 7589 - ocdskingfisher.views.add-view - INFO - Running refresh-views routine
2020-11-05 23:19:50,135 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'initial-functions', 'initial-flatten'}
2020-11-05 23:19:50,173 - 7594 - ocdskingfisher.views.refresh-views - INFO - Time for initial-flatten: 0.020632266998291016s
2020-11-05 23:19:50,175 - 7593 - ocdskingfisher.views.refresh-views - INFO - Time for initial-functions: 0.022427082061767578s
2020-11-05 23:19:50,176 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'middle-tmp_release_summary'}
2020-11-05 23:21:54,758 - 7595 - ocdskingfisher.views.refresh-views - INFO - Time for middle-tmp_release_summary: 124.58016443252563s
2020-11-05 23:21:54,760 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'middle-tender', 'middle-parties_summary', 'middle-awards', 'middle-planning', 'middle-contracts'}
2020-11-05 23:22:03,603 - 7599 - ocdskingfisher.views.refresh-views - INFO - Time for middle-planning: 8.840307474136353s
2020-11-05 23:23:22,918 - 7598 - ocdskingfisher.views.refresh-views - INFO - Time for middle-awards: 88.15504884719849s
2020-11-05 23:24:20,146 - 7600 - ocdskingfisher.views.refresh-views - INFO - Time for middle-contracts: 145.38317942619324s
2020-11-05 23:24:22,906 - 7596 - ocdskingfisher.views.refresh-views - INFO - Time for middle-tender: 148.14393591880798s
2020-11-05 23:24:49,800 - 7597 - ocdskingfisher.views.refresh-views - INFO - Time for middle-parties_summary: 175.03752088546753s
2020-11-05 23:24:49,802 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'middle-contract_items_summary', 'middle-agg_release_party', 'middle-parties_buyer_summary', 'middle-contract_implementation_transactions_summary', 'middle-planning_milestones_summary', 'middle-parties_procuringentity_summary', 'middle-contract_milestones_summary', 'middle-contract_implementation_documents_summary', 'middle-contract_implementation_milestones_summary', 'middle-tender_items_summary', 'middle-award_suppliers_summary', 'middle-parties_tenderers_summary', 'middle-tender_documents_summary', 'middle-award_documents_summary', 'middle-tender_milestones_summary', 'middle-planning_documents_summary', 'middle-award_items_summary', 'middle-contract_documents_summary'}
2020-11-05 23:24:49,852 - 7605 - ocdskingfisher.views.refresh-views - INFO - Time for middle-planning_milestones_summary: 0.04582667350769043s
2020-11-05 23:24:49,853 - 7597 - ocdskingfisher.views.refresh-views - INFO - Time for middle-planning_documents_summary: 0.042263031005859375s
2020-11-05 23:24:50,823 - 7594 - ocdskingfisher.views.refresh-views - INFO - Time for middle-contract_implementation_milestones_summary: 1.0169601440429688s
2020-11-05 23:24:52,163 - 7601 - ocdskingfisher.views.refresh-views - INFO - Time for middle-contract_items_summary: 2.359220504760742s
2020-11-05 23:24:52,261 - 7607 - ocdskingfisher.views.refresh-views - INFO - Time for middle-contract_milestones_summary: 2.455061435699463s
2020-11-05 23:24:52,400 - 7608 - ocdskingfisher.views.refresh-views - INFO - Time for middle-contract_implementation_documents_summary: 2.5938854217529297s
2020-11-05 23:25:01,531 - 7605 - ocdskingfisher.views.refresh-views - INFO - Time for middle-award_items_summary: 11.678273677825928s
2020-11-05 23:25:01,656 - 7596 - ocdskingfisher.views.refresh-views - INFO - Time for middle-tender_milestones_summary: 11.845496654510498s
2020-11-05 23:25:10,700 - 7598 - ocdskingfisher.views.refresh-views - INFO - Time for middle-tender_documents_summary: 20.890358686447144s
2020-11-05 23:25:33,723 - 7604 - ocdskingfisher.views.refresh-views - INFO - Time for middle-contract_implementation_transactions_summary: 43.91775345802307s
2020-11-05 23:25:42,087 - 7599 - ocdskingfisher.views.refresh-views - INFO - Time for middle-parties_tenderers_summary: 52.27796745300293s
2020-11-05 23:26:02,372 - 7597 - ocdskingfisher.views.refresh-views - INFO - Time for middle-contract_documents_summary: 72.51907396316528s
2020-11-05 23:26:31,411 - 7595 - ocdskingfisher.views.refresh-views - INFO - Time for middle-award_suppliers_summary: 101.60428500175476s
2020-11-05 23:26:46,431 - 7600 - ocdskingfisher.views.refresh-views - INFO - Time for middle-award_documents_summary: 116.62115502357483s
2020-11-05 23:26:58,882 - 7593 - ocdskingfisher.views.refresh-views - INFO - Time for middle-tender_items_summary: 129.07556629180908s
2020-11-05 23:27:11,538 - 7602 - ocdskingfisher.views.refresh-views - INFO - Time for middle-agg_release_party: 141.73408675193787s
2020-11-05 23:27:25,270 - 7603 - ocdskingfisher.views.refresh-views - INFO - Time for middle-parties_buyer_summary: 155.46502947807312s
2020-11-05 23:28:14,055 - 7606 - ocdskingfisher.views.refresh-views - INFO - Time for middle-parties_procuringentity_summary: 204.24847841262817s
2020-11-05 23:28:14,056 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'middle-agg_planning', 'middle-planning_summary', 'middle-tender_summary', 'middle-agg_tender', 'middle-agg_milestones', 'middle-awards_summary', 'middle-agg_documents'}
2020-11-05 23:28:14,087 - 7594 - ocdskingfisher.views.refresh-views - INFO - Time for middle-agg_planning: 0.028896093368530273s
2020-11-05 23:28:14,090 - 7605 - ocdskingfisher.views.refresh-views - INFO - Time for middle-agg_milestones: 0.030417680740356445s
2020-11-05 23:28:14,091 - 7601 - ocdskingfisher.views.refresh-views - INFO - Time for middle-planning_summary: 0.0320744514465332s
2020-11-05 23:28:15,048 - 7608 - ocdskingfisher.views.refresh-views - INFO - Time for middle-agg_tender: 0.9889602661132812s
2020-11-05 23:28:46,701 - 7598 - ocdskingfisher.views.refresh-views - INFO - Time for middle-agg_documents: 32.641178607940674s
2020-11-05 23:28:58,779 - 7607 - ocdskingfisher.views.refresh-views - INFO - Time for middle-tender_summary: 44.72035193443298s
2020-11-05 23:28:58,780 - 7596 - ocdskingfisher.views.refresh-views - INFO - Time for middle-awards_summary: 44.71987342834473s
2020-11-05 23:28:58,781 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'middle-contracts_summary', 'middle-agg_awards'}
2020-11-05 23:29:36,436 - 7599 - ocdskingfisher.views.refresh-views - INFO - Time for middle-agg_awards: 37.65410256385803s
2020-11-05 23:29:37,594 - 7604 - ocdskingfisher.views.refresh-views - INFO - Time for middle-contracts_summary: 38.81165170669556s
2020-11-05 23:29:37,595 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'middle-agg_contracts'}
2020-11-05 23:29:57,474 - 7597 - ocdskingfisher.views.refresh-views - INFO - Time for middle-agg_contracts: 19.878182888031006s
2020-11-05 23:29:57,476 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'middle-release'}
2020-11-05 23:30:43,236 - 7595 - ocdskingfisher.views.refresh-views - INFO - Time for middle-release: 45.75869035720825s
2020-11-05 23:30:43,237 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'final-foreign-key-relationships'}
2020-11-05 23:30:45,298 - 7600 - ocdskingfisher.views.refresh-views - INFO - Time for final-foreign-key-relationships: 2.0594289302825928s
2020-11-05 23:30:45,299 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'final-docs'}
2020-11-05 23:30:46,361 - 7593 - ocdskingfisher.views.refresh-views - INFO - Time for final-docs: 1.0605733394622803s
2020-11-05 23:30:46,362 - 7589 - ocdskingfisher.views.refresh-views - INFO - Running {'final-drop'}
2020-11-05 23:30:49,125 - 7602 - ocdskingfisher.views.refresh-views - INFO - Time for final-drop: 2.7613768577575684s
2020-11-05 23:30:49,133 - 7589 - ocdskingfisher.views.refresh-views - INFO - Total time: 659.0096645355225s
2020-11-05 23:30:49,134 - 7589 - ocdskingfisher.views.add-view - INFO - Running field-counts routine
2020-11-05 23:30:49,143 - 7589 - ocdskingfisher.views.field-counts - INFO - Processing collection ID 1530
2020-11-05 23:30:49,143 - 7589 - ocdskingfisher.views.field-counts - INFO - Processing collection ID 1531
2020-11-05 23:30:49,144 - 7589 - ocdskingfisher.views.field-counts - INFO - Processing collection ID 1532
2020-11-05 23:59:01,698 - 7589 - ocdskingfisher.views.field-counts - INFO - Time for collection ID 1530: 1692.5545709133148s
2020-11-05 23:59:01,700 - 7589 - ocdskingfisher.views.field-counts - INFO - Time for collection ID 1531: 1692.5556094646454s
Traceback (most recent call last):
  File "ocdskingfisher-views-cli", line 5, in <module>
    cli()
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/.ve/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/cli.py", line 239, in add_view
    field_counts(schema)
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/cli.py", line 387, in field_counts
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/cli.py", line 364, in _run_collection
    """, {'id': collection}))
  File "/home/ocdskfp/ocdskingfisherviews/ocdskingfisherviews/db.py", line 46, in all
    return self.cursor.fetchall()
psycopg2.ProgrammingError: no results to fetch
```

**Did you attempt a fix?**

No

**How soon do you need a fix?**

As soon as possible as the view is required for publisher feedback.

**Comment by jpmckinney** [comment]
Looking into it.

**Comment by jpmckinney** [comment]
It completed without error. It might have been fixed by the new version.
